{{ if .Values.kafka.enabled }}
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 2Gi
  authorization:
    type: rbac
    superUsers:
      - User: kafka-master
  metricReporter:
    enabled: true
  listeners:
    # internal:
    #   authentication:
    #     type: plain
    #     jaasConfig:
    #       secretRef: credential
    #   tls:
    #     enabled: false 
    external:
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: false
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: kafka
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
{{ end }}    